version: '3.8'

services:
  app:
    image: mcr.microsoft.com/vscode/devcontainers/javascript-node:0-16-bullseye,
    volumes:
      - /:/host

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
    privileged: true
