version: '3.8'

services:
  app:
    image: mcr.microsoft.com/devcontainers/universal:2
    network_mode: "host"
    volumes:
      - /:/host

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
    privileged: true
